version: '3.7'

services: 
  presto:
    image: ahanaio/prestodb-sandbox:0.257
    container_name: presto
    ports: 
      - 8080:8080
    # volumes: 
    #   - ./presto/etc:/opt/presto-server/etc

  # superset:
  #   image: apache/superset
  #   container_name: superset
  #   ports: 
  #     - 8088:8088
  #   depends_on: 
  #     - presto

  # dbeaver:
  #   image: dbeaver/cloudbeaver:21.1.0
  #   container_name: dbeaver
  #   ports: 
  #     - 8978:8978
  #   volumes: 
  #     - ./dbeaver/workspace:/opt/cloudbeaver/workspace
  #   depends_on: 
  #     - presto
  
  ranger-admin:
    image: ranger-admin:1.0
    build: 
      context: ./ranger
      dockerfile: Dockerfile
    container_name: ranger-admin
    ports:
      - 6080:6080
    depends_on:
      - ranger-mysql
      - ranger-solr

  ranger-mysql:
    image: mysql:8.0.26
    container_name: ranger-mysql
    ports:
      - 3306:3306
    volumes:
      - ./ranger/mysql:/etc/mysql/conf.d
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: rangeradmin
      MYSQL_PASSWORD: rangeradmin
      MYSQL_DATABASE: ranger

  ranger-solr:
    image: solr:8.9.0
    container_name: ranger-solr
    ports:
      - 8983:8983
    volumes:
      - ./ranger/solr:/opt/solr/server/solr/configsets/ranger_audits/conf
    entrypoint:
      - solr-precreate
      - ranger_audits
      - /opt/solr/server/solr/configsets/ranger_audits


# docker exec -it superset superset fab create-admin \
#           --username admin \
#           --firstname Superset \
#           --lastname Admin \
#           --email admin@superset.com \
#           --password admin

# docker exec -it superset superset db upgrade

# docker exec -it superset superset init
