version: '3.7'

networks: 
  presto:

services:
 
  # The prestodb-sandbox container includes latest Presto (from Prestodb.io) as well as the Presto CLI.
  presto:
    image: ahanaio/prestodb-sandbox:0.257
    container_name: presto
    ports: 
      - 8080:8080
    networks: 
      - presto
    volumes: 
      - ./presto/conf:/opt/presto-server/etc
      - ./presto/data:/var/lib/presto

  # superset:
  #   image: apache/superset
  #   container_name: superset
  #   ports: 
  #     - 8088:8088
  #   depends_on: 
  #     - presto

  # cloudbeaver:
  #   image: dbeaver/cloudbeaver:21.1.0
  #   container_name: cloudbeaver
  #   ports: 
  #     - 8978:8978
  #   volumes: 
  #     - ./dbeaver/workspace:/opt/cloudbeaver/workspace
  #   networks:
  #     - presto
  
  ranger-admin:
    image: ranger-admin:1.0
    build: 
      context: ./ranger
      dockerfile: Dockerfile
    container_name: ranger-admin
    ports:
      - 6080:6080
    depends_on:
      - mysql
      - ranger-solr
    networks: 
      - presto

  mysql:
    image: mysql:8.0.26
    container_name: mysql
    ports:
      - 3306:3306
    volumes:
      - ./mysql/conf:/etc/mysql/conf.d
      - ./mysql/initdb.d:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: password
    networks: 
      - presto

  ranger-solr:
    image: solr:8.9.0
    container_name: ranger-solr
    ports:
      - 8983:8983
    volumes:
      - ./ranger/solr:/opt/solr/server/solr/configsets/ranger_audits/conf
    entrypoint:
      - solr-precreate
      - ranger_audits
      - /opt/solr/server/solr/configsets/ranger_audits
    networks: 
      - presto


# docker exec -it superset superset fab create-admin \
#           --username admin \
#           --firstname Superset \
#           --lastname Admin \
#           --email admin@superset.com \
#           --password admin

# docker exec -it superset superset db upgrade

# docker exec -it superset superset init


  # mysql-workbench:
  #   image: ghcr.io/linuxserver/mysql-workbench:version-8.0.26
  #   container_name: mysql-workbench
  #   environment:
  #     - PUID=1000
  #     - PGID=1000
  #     - TZ=America/Sao_Paulo
  #   ports:
  #     - 3000:3000
  #   cap_add:
  #     - IPC_LOCK
  #   networks:
  #     - presto

  # ldap-auth:
  #   image: ghcr.io/linuxserver/ldap-auth:version-3.3.1
  #   container_name: ldap-auth
  #   environment:
  #     - TZ=America/Sao_Paulo
  #     - FERNETKEY= #optional
  #     - CERTFILE= #optional
  #     - KEYFILE= #optional
  #   ports:
  #     - 8888:8888
  #     - 9000:9000
  #   networks:
  #     - presto
  
  # openldap:
  #   image: bitnami/openldap:2.5.5
  #   ports:
  #     - 1389:1389
  #     - 1636:1636
  #   environment:
  #     - LDAP_ADMIN_USERNAME=admin
  #     - LDAP_ADMIN_PASSWORD=adminpassword
  #     - LDAP_USERS=user01,user02
  #     - LDAP_PASSWORDS=password1,password2
  #   networks:
  #     - presto
  #   volumes:
  #     - ./openldap_data:/bitnami/openldap

  hive:
    image: hive:0.1
    build: 
      context: ./hive
      dockerfile: Dockerfile
    container_name: hive
    ports: 
      - 9083:9083
    networks: 
      - presto

  hue:
    image: hue:4.10.0
    build: 
      context: hue
      dockerfile: Dockerfile
    container_name: hue
    ports: 
      - 8888:8888
    volumes: 
      - ./hue/hue.ini:/usr/share/hue/desktop/conf/z-hue-overrides.ini
    networks: 
      - presto
    depends_on: 
      - mysql
