version: '3.7'

networks: 
  presto:

services:
 
  # The prestodb-sandbox container includes latest Presto (from Prestodb.io) as well as the Presto CLI.
  presto:
    image: meu-presto:0.259
    build: 
      context: ./presto
      dockerfile: Dockerfile
    container_name: presto
    ports: 
      - 8080:8080
    networks: 
      - presto
    volumes: 
      # - ./presto/data:/var/lib/presto
      - ./presto/conf:/opt/presto-server/etc

    # docker container cp ranger-presto-plugin presto:/opt/presto-server/plugin

  # trino:
  #   image: meu-trino:360
  #   build: 
  #     context: ./trino
  #     dockerfile: Dockerfile
  #   container_name: trino
  #   ports: 
  #     - 8080:8080
  #   networks: 
  #     - presto
  #   volumes: 
  #     - ./trino/conf:/etc/trino
  #     - ./trino/ranger-presto-plugin:/usr/lib/trino/plugin/ranger-trino/plugin

    # docker container cp ranger-presto-plugin trino:/usr/lib/trino/plugin

  # superset:
  #   image: apache/superset:1.2.0
  #   container_name: superset
  #   ports: 
  #     - 8088:8088
  #   depends_on: 
  #     - presto
  #   networks: 
  #     - presto

# docker exec -it superset superset fab create-admin \
#           --username admin \
#           --firstname Superset \
#           --lastname Admin \
#           --email admin@superset.com \
#           --password admin

# docker exec -it superset superset db upgrade

# docker exec -it superset superset init

  # cloudbeaver:
  #   image: dbeaver/cloudbeaver:21.1.0
  #   container_name: cloudbeaver
  #   ports: 
  #     - 8978:8978
  #   volumes: 
  #     - ./dbeaver/workspace:/opt/cloudbeaver/workspace
  #   networks:
  #     - presto
  #   # user: cbadmin
  #   # pass: password

  ranger:
    image: ranger-admin:1.0
    build: 
      context: ./ranger
      dockerfile: Dockerfile
    container_name: ranger
    ports:
      - 6080:6080
    depends_on:
      - mysql
      - solr
    networks:
      - presto
  
    # user: admin
    # pass: ranger123

  solr:
    image: solr:8.9.0
    container_name: solr
    ports:
      - 8983:8983
    volumes:
      - ./solr:/opt/solr/server/solr/configsets/ranger_audits/conf
    entrypoint:
      - solr-precreate
      - ranger_audits
      - /opt/solr/server/solr/configsets/ranger_audits
    networks:
      - presto

  mysql:
    image: mysql:8.0.26
    container_name: mysql
    ports:
      - 3306:3306
    volumes:
      - ./mysql/conf:/etc/mysql/conf.d
      - ./mysql/initdb.d:/docker-entrypoint-initdb.d
      - ./mysql/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: password
    networks:
      - presto

  # mysql-workbench:
  #   image: ghcr.io/linuxserver/mysql-workbench:version-8.0.26
  #   container_name: mysql-workbench
  #   environment:
  #     - PUID=1000
  #     - PGID=1000
  #     - TZ=America/Sao_Paulo
  #   ports:
  #     - 3000:3000
  #   cap_add:
  #     - IPC_LOCK
  #   networks:
  #     - presto

  hive-metastore:
    image: hive-metastore:0.1
    build: 
      context: ./hive
      dockerfile: Dockerfile
    container_name: hive-metastore
    ports: 
      - 9083:9083
    networks: 
      - presto
